name: Asterisk Unit Tests
run-name: ${{ github.actor }} has triggered a run of Asterisk Unit Tests
on:
  workflow_call:

jobs:
  AsteriskUnitTests:
    runs-on: ubuntu-latest
    container:
      image: public.ecr.aws/t8c9l3c7/asteriskci-agent-rocky8:latest

    steps:
      - name: Setup for local ACT
        if: ${{ env.ACT }}
        run: |
          if [ -z "${ASTERISK_CI_URL}" ] || [ -z "${ASTERISK_URL}" ] ; then
            echo "::error::ASTERISK_CI_URL and ASTERISK_URL must be set in the environment"
            exit 1
          fi
          echo "::notice::Setting ASTERISK_CI_URL and ASTERISK_URL from environment"
          echo "PWD: $PWD"
          mount

      - name: Checkout Asterisk
#        if: ${{ !env.ACT }}
        uses: actions/checkout@v3
        with:
          path: 'asterisk'
          # Whether to execute `git clean -ffdx && git reset --hard HEAD` before fetching
          # Default: true
          clean: true
          fetch-depth: 1
          # Add repository path as safe.directory for Git global config by running `git
          # config --global --add safe.directory <path>`
          # Default: true
          set-safe-directory: true

      - name: Setup Asterisk Build Environment
        run: |
          cd asterisk
          echo "PWD: $PWD"
          mkdir -p /srv/cache/externals /srv/cache/sounds /srv/cache/ccache || :
          chown -R asteriskci:users /srv/cache
          chmod g+rw /srv/cache/ccache
          chmod g+s /srv/cache/ccache
          mkdir -p tests/CI/output || :
          chown -R asteriskci:users tests/CI/output

      - name: Build Asterisk
        run: |
          cd asterisk
          echo "PWD: $PWD"
          if [ -f ./tests/CI/output/is-built ] ; then
            echo "Asterisk is already built"
            exit 0
          fi
          ./tests/CI/buildAsterisk.sh --github --branch-name=master --output-dir=./tests/CI/output
          touch ./tests/CI/output/is-built

      - name: Install Asterisk
        if: ${{ success() }}
        run: |
          cd asterisk
          echo "PWD: $PWD"
          if [ -f ./tests/CI/output/is-installed ] ; then
            echo "Asterisk is already installed"
            exit 0
          fi
          ./tests/CI/installAsterisk.sh --github --uninstall-all --branch-name=master --user-group=asteriskci:users 
          touch ./tests/CI/output/is-installed

      - name: Run Unit Tests
        if: ${{ success() }}
        run: |
          cd asterisk
          echo "PWD: $PWD"
          tests/CI/runUnittests.sh --no-expect --github \
            --user-group=asteriskci:users \
            --output-dir=./tests/CI/output \
            --output-xml=./tests/CI/output/unittests-results.xml

      - name: Save Output
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: Test Results
          path: asterisk/tests/CI/output

      - name: Save Event Payload
        uses: actions/upload-artifact@v3
        with:
          name: Event File
          path: ${{ github.event_path }}
